export const products =[
    {
        id:1,
        img:"https://github.com/LilianWilt120100/portfolioimages/blob/main/mediatek.png?raw=true",
        link:"https://github.com/LilianWilt120100/Mediatek"
    },
    {
        id:2,
        img:"https://github.com/LilianWilt120100/portfolioimages/blob/main/monsterproject.png?raw=true",
        link:"https://github.com/LilianWilt120100/ProjetJS"
    },
    {
        id:3,
        img:"https://github.com/LilianWilt120100/portfolioimages/blob/main/paintproject.png?raw=true",
        link:"https://github.com/LilianWilt120100/ProjetIHM"
    },
    {
        id:4,
        img:"https://github.com/LilianWilt120100/portfolioimages/blob/main/projetZeldiablo.png?raw=true",
        link:"https://github.com/LilianWilt120100/2020_coo_zeldiablo_tabbone4u_brullard4u_lampert13u_wilt2u"
    },
    {
        id:5,
        img:"https://github.com/LilianWilt120100/portfolioimages/blob/main/projetpoquemont.png?raw=true",
        link:"https://github.com/LilianWilt120100/ProjetPoquemont"
    },
    {
        id:6,
        img:"https://github.com/LilianWilt120100/portfolioimages/blob/main/projetwebS1.png?raw=true",
        link:"https://github.com/LilianWilt120100/ProjetWebS1"
    }
]